Gt 155 uart name packed string interfaceitem
altendky/pm pull request #11
Opened 2021-05-12 18:36 UTC by epcAnker

2021-05-13 17:20 UTC, gordon-epc commented
Right off the bat, I can see you will need to reformat the file using black.

2021-05-13 17:44 UTC, gordon-epc requested changes

2021-05-13 17:44 UTC, gordon-epc commented on src/epcpm/parameterstointerface.py
> +            return f"{model_variable}.{parameter.abbreviation}"
Consider replacing with arguably not easier to read one liner:
`return f"{'&' if reference else ''}{model_variable}.{parameter.abbreviation}"`

2021-05-13 17:44 UTC, gordon-epc commented on src/epcpm/parameterstointerface.py
> +            return f"interfaceItem_variable_{uuid_}"
Consider replacing with arguably not easier to read one liner:
`return f"{'&' if reference else ''}interfaceItem_variable_{uuid_}"`

2021-05-18 14:42 UTC, altendky requested changes

2021-05-18 14:42 UTC, altendky commented on src/epcpm/parameterstointerface.py
> +    if parameter.internal_type == "UartName":
I think (maybe) this function so far doesn't have any significant type awareness?  Perhaps this goes outside and comes in more like `variable_or_getter_setter`?

2021-05-21 21:18 UTC, altendky requested changes
Just small stuff this time. `:]`

2021-05-21 21:18 UTC, altendky commented on src/epcpm/parameterstointerface.py
> +    # By Default will return reference to the variable unless reference parameter == false.
```suggestion
```

2021-05-21 21:18 UTC, altendky commented on src/epcpm/parameterstointerface.py
> +
Just to reduce diff noise.  `*shrug*`
```suggestion
```

2021-05-21 21:18 UTC, altendky commented on src/epcpm/parameterstointerface.py
> +    if scale_factor_variable is not "NULL":
Short strings tend to be interned and thus `is` works, but it is not guaranteed.

```suggestion
    if scale_factor_variable != "NULL":
```

2021-05-21 21:18 UTC, altendky commented on src/epcpm/parameterstointerface.py
> +    if sunspec_variable is not "NULL":
```suggestion
    if sunspec_variable != "NULL":
```

2021-05-21 21:46 UTC, epcAnker commented on src/epcpm/parameterstointerface.py
> +    # By Default will return reference to the variable unless reference parameter == false.
good catch

2021-05-21 22:01 UTC, gordon-epc approved these changes
Run black and it should be all good to go.

2021-06-11 00:12 UTC, merged