feat (GT-129): add generated staticmodbus.json
altendky/pm pull request #13
Opened 2021-06-03 01:11 UTC by gordon-epc

Add a generated staticmodbus.json file.

2021-06-04 15:01 UTC, altendky requested changes
Presumably the extra fields noted in https://github.com/epcpower/grid-tied/pull/59#pullrequestreview-676376372 will be dealt with here.

2021-06-07 21:11 UTC, gordon-epc commented on src/epcpm/sunspectostaticmodbus.py
> +@click.option("--output_staticmodbus_filename")
Made this change in c229af5275782dd9871f1bc720612b4a3ec84b12

2021-06-07 21:12 UTC, gordon-epc commented on src/epcpm/sunspectostaticmodbus.py
> +    # It is most likely one time use code.
The comment added as a docstring and the contents of the string are much briefer in c229af5275782dd9871f1bc720612b4a3ec84b12

2021-06-07 21:15 UTC, gordon-epc commented on src/epcpm/sunspectostaticmodbus.py
> +    sunspec_to_staticmodbus_generator()
Removed the `__main__` code. Moved the file to the `epcpm/cli` directory to match with other cli code. Added the group "utility" and put the sunspec to staticmodbus script plus a "transition" command into the "utility" group. All this done in c229af5275782dd9871f1bc720612b4a3ec84b12

2021-06-09 01:48 UTC, gordon-epc commented
Removal of the fields mentioned in [epcpower/gridtied #59](https://github.com/epcpower/grid-tied/pull/59#pullrequestreview-676376372) has been done.

2021-06-11 22:29 UTC, altendky approved these changes

2021-06-12 00:45 UTC, merged