feat (GT-130): static modbus interface generation
altendky/pm pull request #14
Opened 2021-06-03 01:41 UTC by gordon-epc

Static modbus interface generation for grid-tied.

2021-08-16 15:13 UTC, altendky requested changes

2021-08-16 19:26 UTC, gordon-epc commented on src/epcpm/parameterstointerface.py
> +    "bitfield32": "sunsU32",
Added comment in c3c1694e82910cd9ee229743dddd85e94b23421c

2021-08-16 19:26 UTC, gordon-epc commented on src/epcpm/parameterstointerface.py
> +        # # TODO: This needs to change to return staticmodbusInterface variable name, whenever that exists.
Updated comment + removed commented out code in c3c1694e82910cd9ee229743dddd85e94b23421c

2021-08-16 19:27 UTC, gordon-epc commented on src/epcpm/parameterstointerface.py
> +            f".variable = {staticmodbus_variable},",
No action taken. This will be handled when staticmodbus.common.variable is removed in the future.

2021-08-17 17:55 UTC, altendky approved these changes
As always, thanks for the work.  Except I'm not sure I actually say that here.  So, thank you.

2021-08-17 18:27 UTC, merged