Spike/sc 1929 rm dc
altendky/pm pull request #96
Opened 2024-06-06 21:24 UTC by abnepc

## Jira Story
[SC-1929](https://epcpower.atlassian.net/browse/SC-1929)
## About
Investigate upgrading from `python3.7`
## Associated Pull Requests
* [sunspec-demo](https://github.com/epcpower/sunspec-demo/pull/34)
* [stlib](https://github.com/epcpower/stlib/pull/47)
* [st](https://github.com/epcpower/st/pull/48)
* [grid-tied](https://github.com/epcpower/grid-tied/pull/664)
* [rm-dc](https://github.com/epcpower/rm-dc/pull/20)
* [m-bcu](https://github.com/epcpower/m-bcu/pull/6)
* [m-pm](https://github.com/epcpower/m-pm/pull/3)
* [m-tcu](https://github.com/epcpower/m-tcu/pull/44)

## Reproduction Steps
N/A
## Validation
Check that CI is using `python3.8`

[SC-1929]: https://epcpower.atlassian.net/browse/SC-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-12 23:35 UTC, gordon-epc requested changes

2024-06-12 23:35 UTC, gordon-epc commented on .github/workflows/ci.yml
Match the change in the regular pm 1929 PR.
```
on:
  push:
    branches:
      - '**' #double star includes a '/'.  single star doesnt match a '/'
    tags:
      - '**' #double star includes a '/'.  single star doesnt match a '/'
```

2024-06-13 00:00 UTC, abnepc commented on .github/workflows/ci.yml
[226e00d](https://github.com/epcpower/pm/pull/96/commits/226e00dd11b54198de577b53fef55a31d36c0ddc)

2024-06-14 23:58 UTC, gordon-epc approved these changes

2024-06-17 23:30 UTC, merged