Story/ba 510 rm dc
altendky/pm pull request #97
Opened 2024-06-25 17:54 UTC by abnepc

## Jira Story
[BA-510](https://epcpower.atlassian.net/browse/BA-510)

## About
Update Poetry version from 1.1.15 to 1.5.1.

## Associated Pull Requests
N/A

## Reproduction Steps

## Validation

[BA-510]: https://epcpower.atlassian.net/browse/BA-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-28 00:45 UTC, gordon-epc requested changes

2024-06-28 00:45 UTC, gordon-epc commented on pyproject.toml
Add this comment before `version`:

```
# The version variable below is set to the generic build placeholder "0.0.0".
# (In other words: leave alone!) During CI, poetry dynamic versioning
# modifies the __version__ variable in the applicable __init__.py file.
```

2024-06-28 00:45 UTC, gordon-epc commented on pyproject.toml
Remove this line:
`poetry-dynamic-versioning = "^0.13.1"`

2024-06-28 00:45 UTC, gordon-epc commented on pyproject.toml
>  build-backend = "poetry.core.masonry.api"
```suggestion
build-backend = "poetry_dynamic_versioning.backend"
```

2024-06-28 00:45 UTC, gordon-epc commented on .github/workflows/ci.yml
Add the `ChefBuildError` workaround. We may as well do it now, as I see it affecting more and more repos.

2024-06-28 01:42 UTC, abnepc commented on pyproject.toml
[40a7e55](https://github.com/epcpower/pm/pull/97/commits/40a7e55afd808adf569a0b9ee607e5a7878f9895)

2024-06-28 01:42 UTC, abnepc commented on pyproject.toml
>  build-backend = "poetry.core.masonry.api"
[40a7e55](https://github.com/epcpower/pm/pull/97/commits/40a7e55afd808adf569a0b9ee607e5a7878f9895)

2024-06-28 01:43 UTC, abnepc commented on pyproject.toml
[40a7e55](https://github.com/epcpower/pm/pull/97/commits/40a7e55afd808adf569a0b9ee607e5a7878f9895)

2024-06-28 01:47 UTC, abnepc commented on .github/workflows/ci.yml
[f92c6dc](https://github.com/epcpower/pm/pull/97/commits/f92c6dc535415bf9d09a5e007e39e49dc7863c07)

2024-06-28 01:47 UTC, abnepc commented on pyproject.toml
>  build-backend = "poetry.core.masonry.api"
[79206fb](https://github.com/epcpower/pm/pull/97/commits/79206fba3b40e133b352add0207f56af00873f4f)

2024-07-03 21:29 UTC, gordon-epc approved these changes

2024-07-03 21:29 UTC, merged